### ISSUE TITLE
Would you consider adding a "Inclusion Tag"?

### ISSUE THREAD

**Issue by thht** [dldevinc/jinja2-simple-tags#6]
Hi and first of all thanks a lot for this project!

I am going to develop an equivalent of the [InclusionTag](https://django-classy-tags.readthedocs.io/en/latest/reference.html#classytags.helpers.InclusionTag) as found in [django-classy-tags](https://django-classy-tags.readthedocs.io/en/latest/index.html) based on this project.

I can either put it in an independent project or, if you are interested, contribute to this project.

I would, of course, follow your code styles, provide unit tests and be open to feedback.

What do you say?

**Comment by pix666** [comment]
@thht Thank you for your interest in contributing to my project. Please feel free to submit a Pull Request with your code.
I'll look forward to reviewing your contribution and providing feedback. Thank you again.

**Comment by pix666** [comment]
@thht Hi there,

The InclusionTag feature you mentioned has been added to the development branch of the project.

**Comment by pix666** [comment]
`InclusionTag` was added in version 0.6.0
